name: Deploy Development

on:
  push:
    branches: ["dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-app-image:
    uses: ./.github/workflows/build-app.yml
    with:
      ecr_repo: dev-airflow
      region: eu-west-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_123456789_CICD_USER }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_123456789_CICD_USER }}

  deploy-infra:
    needs: ["build-app-image"]
    uses: ./.github/workflows/deploy-infra.yml
    with:
      terraform_workspace: dev
    secrets: inherit
